image: Visual Studio 2019

platform:
  - x64

init:
  - git config --global core.autocrlf input

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 16 x64
  - npm i --legacy-peer-deps

environment:
  GH_TOKEN:
    secure: kZMGyhBmfPsJKEryrd+I7gTEudm8tW0jSrKKhtT/3fbqKQzndTWp47C1Eetx5kFs

build_script:
  - yarn release:win
  - Compress-Archive -Path dist\*x64.exe, dist\*arm64.exe, dist\*x64.exe.blockmap, dist\*arm64.exe.blockmap -DestinationPath dist\HeroicWin.zip

test: off

artifacts:
  - path: dist\HeroicWin.zip
    name: Heroic_setup

deploy:
  - provider: Webhook
    url: https://app.signpath.io/API/v1/f7f99393-5adb-408c-8ca3-67e07cfe31e6/Integrations/AppVeyor?ProjectSlug=HeroicGamesLauncher&SigningPolicySlug=release-signing
    authorization:
      secure: 0xlTR3DMFume9u66Kf7WkMP1sMl9S7GMoP8vZgrIAKr/eHXCKfLBM+LbmACtCHWoqeTXVIuAYCfUJIPoJt1SBA==
