image: Visual Studio 2019

platform:
  - x64

cache:
  - node_modules

install:
  - ps: Install-Product node 16 x64
  - npm i --legacy-peer-deps

environment:
  GH_TOKEN:
    secure: kZMGyhBmfPsJKEryrd+I7gTEudm8tW0jSrKKhtT/3fbqKQzndTWp47C1Eetx5kFs

build:
  verbosity: detailed

build_script:
  - yarn dist:win

artifacts:
  - path: 'dist/Heroic*.exe'
    name: Heroic_setup

deploy:
  - provider: Webhook
    url: https://app.signpath.io/API/v1/f7f99393-5adb-408c-8ca3-67e07cfe31e6/Integrations/AppVeyor?ProjectSlug=HeroicGamesLauncher&SigningPolicySlug=test-signing
    authorization:
      secure: 0xlTR3DMFume9u66Kf7WkMP1sMl9S7GMoP8vZgrIAKr/eHXCKfLBM+LbmACtCHWoqeTXVIuAYCfUJIPoJt1SBA==
