image: Visual Studio 2019

platform:
  - x64

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 16 x64
  - npm i --legacy-peer-deps

environment:
  GH_TOKEN:
    secure: kZMGyhBmfPsJKEryrd+I7gTEudm8tW0jSrKKhtT/3fbqKQzndTWp47C1Eetx5kFs

build_script:
  - npm run dist:win

test: off

artifacts:
  - path: dist/Heroic*.exe
    name: Heroic_EXE

deploy:
  - provider: Webhook
    url: https://app.signpath.io/API/v1/f7f99393-5adb-408c-8ca3-67e07cfe31e6/Integrations/AppVeyor?ProjectSlug=HeroicGamesLauncher&SigningPolicySlug=test-signing
    authorization:
      secure: h7E0ayuitukQHwIttJmgV0dQX7BWSbeV8xds1CczLpbYUA/i9IMXR6wA629OfwXCQJA+RY/NoxKJUUnkLhmwXw==
