version: '3.8'
services:
  playwright:
    image: mcr.microsoft.com/playwright:latest
    volumes:
      - ../:/home/pwuser/e2e
    working_dir: /home/pwuser/e2e
    user: ${USER}
    cap_add:
      - SYS_ADMIN
    environment:
      - ELECTRON_ENABLE_STACK_DUMPING=true
      - ELECTRON_ENABLE_LOGGING=true
      - TEST_PACKAGED=${TEST_PACKAGED}
    network_mode: 'host'
