version: '3.8'
services:
  playwright:
    image: mcr.microsoft.com/playwright:latest
    volumes:
      - ../:/src
    working_dir: /src
    user: ${USER}
    environment:
      - ELECTRON_ENABLE_STACK_DUMPING=true
      - ELECTRON_ENABLE_LOGGING=true
    network_mode: 'host'
