version: '3.8'
services:
  playwright:
    image: mcr.microsoft.com/playwright:latest
    volumes:
      - ../:/src
    working_dir: /src
    environment:
      - ELECTRON_ENABLE_STACK_DUMPING=true
      - ELECTRON_ENABLE_LOGGING=true
      - TEST_PACKAGED=true
    network_mode: 'host'
