name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v2
      - name: Install modules.
        run: yarn
      - name: Build 'src'.
        run: yarn build
      - name: Build 'electron'.
        run: yarn build-electron
      - name: Build artifacts.
        run: |
          sudo apt-get install --no-install-recommends -y libarchive-tools libopenjp2-tools rpm
          yarn dist snap appimage pacman deb rpm --publish=never
      - name: Upload artifacts.
        uses: actions/upload-artifact@v2
        with:
          name: linux-binaries
          path: dist/heroic*
          retention-days: 7
