name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v2
      - name: Install modules.
        run: yarn
      - name: Build 'src'.
        run: yarn build
      - name: Build 'electron'.
        run: yarn build-electron
      - name: Build artifacts.
        run: |
          yarn start
          yarn dist snap
          yarn dist appimage
          yarn dist pacman
          yarn dist deb
          yarn dist rpm
      - name: Upload artifacts.
        uses: actions/upload-artifact@v2
        with:
          name: linux-binaries
          path: dist/heroic*
          retention-days: 7
