name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v2
      - name: Install modules.
        run: npm i -g npm@latest && npm install
      - name: Build 'src'.
        run: npm run build
      - name: Build 'electron'.
        run: npm run build-electron
