name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install modules.
        run: yarn
      - name: Build 'src'.
        run: yarn build
      - name: Build 'electron'.
        run: yarn build-electron
      - name: Build artifacts.
        run: |
          sudo apt-get install --no-install-recommends -y libarchive-tools libopenjp2-tools
          yarn dist appimage --publish=never
      - name: Upload AppImage.
        uses: actions/upload-artifact@v2
        with:
          name: linux-appimage
          path: dist/Heroic-*.AppImage
          retention-days: 7
