name: Code check

on:
  pull_request:
    branches: [main, stable]
  workflow_dispatch:

jobs:
  codecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install node-gyp.
        run: yarn global add node-gyp
      - name: Install modules.
        run: yarn install --frozen-lockfile --verbose
      - name: Check Typescript syntax
        run: yarn codecheck
