name: Code check

on:
  pull_request:
    branches: [main, stable]
  workflow_dispatch:

jobs:
  codecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: linux-yarn-${{ hashFiles('yarn.lock') }}
      - name: Install modules.
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Check Typescript syntax
        run: yarn codecheck
