name: Draft Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  draft-releases:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install --no-install-recommends -y libarchive-tools libopenjp2-tools rpm
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: GH_TOKEN="${{ secrets.WORKFLOW_TOKEN }}" yarn ci-build
