on:
  push:
    branches: [main]
  pull_request:
    branches: [main, stable]
  workflow_dispatch:
    inputs:
      version:
        description: 'Build Flatpak Files'
        required: false
name: Flatpak-CI
jobs:
  flatpak:
    name: 'Flatpak Build'
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install yarn
        run: npm install -g yarn
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install modules.
        run: yarn install
      - name: Build artifacts.
        run: yarn dist:linux appimage --publish=never
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Prepare Flatpak
        run: yarn flatpak:prepare
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: heroicgameslauncher.flatpak
          manifest-path: flatpak-build/com.heroicgameslauncher.hgl.yml
          cache-key: flatpak-builder-${{ github.sha }}
