on:
  push:
    branches: [main]
  pull_request:
    branches: [main, stable]
  workflow_dispatch:
    inputs:
      version:
        description: 'Build Flatpak Files'
        required: false
name: Flatpak-CI
jobs:
  flatpak:
    name: 'Flatpak Build'
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install modules.
        run: npm install
      - name: Build AppImage
        run: npm run dist:flatpak
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
