name: Lint

on:
  pull_request:
    branches: [main, stable]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: linux-yarn-${{ hashFiles('package-lock.json') }}
      - name: Install modules.
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Lint code.
        run: yarn lint
      - name: Prettier code.
        run: yarn prettier
