name: Test E2E Packaged App

on:
  pull_request:
    branches: [main, stable]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install modules.
        run: yarn
      - name: Build and Test
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- yarn test:e2ePackaged
