name: Test

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository.
      uses: actions/checkout@v2
    - name: Install modules.
      run: yarn
    - name: Test and collect coverage.
      run: yarn test:ci --coverage
