name: Test E2E Dev

on:
  pull_request:
    branches: [main, stable]
  workflow_dispatch:

jobs:
  test_dev:
    strategy:
      matrix:
        os: [windows-2022, ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-deps
      - name: Build and Test
        run: yarn test:e2e-ci
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false
