name: Test E2E Dev

on:
  pull_request:
    branches: [main, stable, tests/add_api_tests]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v3
      - name: Build the stack
        run: docker-compose -f docker-compose.yml up
