name: Test E2E Dev

on:
  pull_request:
    branches: [main, stable]
  workflow_dispatch:

jobs:
  test-e2e-dev:
    name: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install modules.
        run: yarn
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - name: Build and Test
        run: yarn test:e2e-ci
