name: Test

on:
  pull_request:
    branches: [main, stable]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v3
      - uses: ./.github/actions/install-deps
      - name: Test
        run: yarn test:ci
